- name: install apache on Ubuntu websersers
  tags: apache,ubuntu
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
  when: ansible_distribution == "Ubuntu"

- name: install apache on Fedora webservers
  tags: apache,fedora
  ansible.builtin.dnf:
    name: httpd
  when: ansible_distribution == "Fedora"

- name: ensure apache is running on Ubuntu
  tags: apache,ubuntu
  ansible.builtin.service:
    name: apache2
    state: started
  when: ansible_distribution == "Ubuntu"

- name: ensure apache is running on Fedora
  tags: apache,fedora
  ansible.builtin.service:
    name: httpd
    state: started
  when: ansible_distribution == "Fedora"

- name: change admin email from default
  tags: fedora,apache
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^Serveradmin'
    line: ServerAdmin somebody@local.dk
  when: ansible_distribution == "Fedora"
  register: httpd

- name: restart httpd on fedora
  tags: apache,fedora
  ansible.builtin.service:
    name: httpd
    state: restarted
  when: httpd.changed


- name: copy html files to site
  tags: apache,ubuntu
  ansible.builtin.copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

